<div class="block block-dashboard-info">
    <div class="block-title"><strong><?= $block->escapeHtml(__('Account Dashboard')) ?></strong></div>
    <div class="block-content">
        <div class="box box-information">
            <strong class="box-title">
                <span><?= $block->escapeHtml(__('Contact Information')) ?></span>
            </strong>
            <div class="box-content">
                <p>Name: <?= $block->escapeHtml($block->getName()) ?></p>
                <p>Email: <?= $block->escapeHtml($block->getCustomer()->getEmail()) ?></p>
                <p>Phone Number: <?= $block->escapeHtml($block->getPhoneNumber()) ?></p>
                <p>Avatar:
                    <image src="<?= $block->escapeHtml($block->getAvatar()) ?>"></image>
                </p>
                <p>Id: <?= $block->escapeHtml($block->getCustomer()->getId()) ?></p>
                <?= $block->getChildHtml('customer.account.dashboard.info.extra'); ?>
            </div>
            <div class="box-actions">
                <a class="action edit" href="<?= $block->escapeUrl($block->getUrl('customer/account/edit')) ?>">
                    <span><?= $block->escapeHtml(__('Edit')) ?></span>
                </a>
                <a href="<?= $block->escapeUrl($block->getChangePasswordUrl()) ?>" class="action change-password">
                    <?= $block->escapeHtml(__('Change Password')) ?>
                </a>
            </div>
        </div>

    </div>
</div>
