<body>
<h2>Movie Landingspage</h2>
    <table style="border: 1px solid ">
        <tr>
            <th style="border: 1px solid">Movie</th>
            <th style="border: 1px solid">Description</th>
            <th style="border: 1px solid">Rating</th>
            <th style="border: 1px solid">Director</th>
            <th style="border: 1px solid">Actor</th>
        </tr>
        <?php
        foreach ($block->getMovies() as $movie){ ?>
        <tr>


            <td style="border: 1px solid"> <?php  echo $movie->getMovie();?> </td>
            <td style="border: 1px solid"> <?php  echo $movie->getDescription();?> </td>
            <td style="border: 1px solid"> <?php  echo $movie->getRating();?> </td>
            <td style="border: 1px solid"> <?php  echo $movie->getDirector();?> </td>
            <td style="border: 1px solid"> <?php  echo $movie->getActor();}?> </td>


        </tr>

    </table>
</body>




